backend:
  name: git-gateway
  branch: main
  # repo: ellyshitiavai/medzonesuppliesltd

media_folder: "static/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: 2f16b791d59241bdc4ca

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Description (Short)", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Detailed Description", name: "body", widget: "markdown", required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
