backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"   # Where uploaded files are stored in repo
public_folder: "/assets/images/uploads" # Public URL path for the media

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
