backend:
  name: git-gateway     # or “github” if you prefer direct GitHub auth
  branch: main          # change this if your default branch is different
  # If using “github” backend, you might need:
  # repo: ellyshitiavai/medzonesuppliesltd

media_folder: "static/uploads"     # where files will be stored in your repo
public_folder: "/uploads"          # how they’re accessed in browser

media_library:
  name: uploadcare
  config:
    publicKey: "your_uploadcare_public_key"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
